import uuid
from datetime import datetime, timezone
from sqlalchemy import Column, String, DateTime, ForeignKey, Text, Integer, Enum as SQLEnum
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship
from app.db.database import Base
import enum

class ReportStatus(str, enum.Enum):
    GENERATED = "generated"      # Auto-generated by system
    REVIEWED = "reviewed"        # Reviewed by teacher
    APPROVED = "approved"        # Approved and ready to send
    SENT = "sent"                # Sent to guardian
    ARCHIVED = "archived"

class StudentReport(Base):
    __tablename__ = "student_reports"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    student_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)
    teacher_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)
    
    month = Column(Integer, nullable=False)
    year = Column(Integer, nullable=False)
    
    # Aggregated metrics and AI insights
    report_data = Column(JSONB, default=dict)
    
    # Teacher input
    teacher_notes = Column(Text, nullable=True)
    status = Column(SQLEnum(ReportStatus), default=ReportStatus.GENERATED)
    
    approved_at = Column(DateTime(timezone=True), nullable=True)
    sent_at = Column(DateTime(timezone=True), nullable=True)
    
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    updated_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))

    # Relationships
    student = relationship("User", foreign_keys=[student_id], lazy="joined")
    teacher = relationship("User", foreign_keys=[teacher_id], lazy="joined")
