"""add education category to student profile

Revision ID: 684f1d0a26e6
Revises: f9f9f9f9f9f9
Create Date: 2026-04-08 20:04:48.582324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '684f1d0a26e6'
down_revision: Union[str, Sequence[str], None] = 'f9f9f9f9f9f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()

    # 1. Drop legacy table safely
    if 'teacher_student_links' in existing_tables:
        op.drop_table('teacher_student_links')
    
    # 2. Add HNSW index safely (should use IF NOT EXISTS pattern)
    op.execute("""
        CREATE INDEX IF NOT EXISTS ix_material_chunks_embedding_hnsw 
        ON material_chunks 
        USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64);
    """)

    # 3. Drop column safely
    if 'topics' in existing_tables:
        existing_cols = [c['name'] for c in inspector.get_columns('topics')]
        if 'content_data' in existing_cols:
            op.drop_column('topics', 'content_data')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('content_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.drop_index('ix_material_chunks_embedding_hnsw', table_name='material_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('teacher_student_links',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('teacher_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('added_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('private_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('teacher_student_links_student_id_fkey')),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('teacher_student_links_teacher_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('teacher_student_links_pkey'))
    )
    op.drop_column('student_profiles', 'education_category')
    # ### end Alembic commands ###
